### ISSUE TITLE
[Feature Request]: Allow to set a path instead of different filename format

### ISSUE THREAD

**Issue by Andreas-Coding** [ramidzkh/fabrishot#21]
Hey guys,

I really like this mod and  used it a lot since discovering it. On thing that bugs me though is that with every screenshot I take I need to rename them according to the instance I took them with and move them to the appropriate folder.

My request would therefore be the ability to set a custom path for where to save the screenshot with things like `{mcversion}` and `{timestamp}` and others as variables for dynamical paths.

**Comment by ramidzkh** [comment]
I know I assigned this to myself half a year ago, but what variables would you want? I'm thinking to have an advanced option for this, where `{standard}` is the default and standard autocompletes to the normal format, but you could do `C:\Screenshots\my modpack\{timestamp} - {world name}.png`

IMO `{mcversion}` isn't that useful since you usually don't copy configs between versions anyway

**Comment by CodexEnt** [comment]
Hi. Right now the resultant name from a snapshot (assuming default 4k) is 
eg. huge_2022-03-16_{time_stamp}.png

At least, I would like the ModPackName and WorldName included, as it is far more descriptive, and maybe other namings could be included in settings panel depending on end use.

{ModPackName} _(optional)__{WorldName}_{PlayerName}(optional)_{Date:Time}

Maybe {ServerName}(optional) for server admins/moderators who might need to take screenshots for any reason.

I may for some reason want to move the screenshots I take in individual instances and  modpacks and put them in my general Images/Games/Minecraft  folder, where you might see that the current naming convention wouldn't mean much in the long run, as I will delete or uninstall past modpacks and wouldn't want to try to remember or rename where these snapshots came from.

Also, perhaps some file format options to save to more compressed formats like the usual jpg, and newer *.webm if uploading to web, and newer compression formats *.avif and *.heic if desired and time allows.

Just adding to the original poster's thoughts as to why more naming conventions would be handy.
