### ISSUE TITLE
Config menu doesn't exist

### ISSUE THREAD

**Issue by Pythagoras-314** [ramidzkh/fabrishot#25]
Note: I might just be stupid and don't know where the config menu is, but anyways

I don't believe the config file for this mod exists in the 1.18 version. It's not in the config folder in .minecraft. That's kinda it.

**Comment by ramidzkh** [comment]
Do you have both modmenu and cloth config? I think the config only generates then, I'll fix that now

**Comment by ramidzkh** [comment]
It'll load a config regardless, but it won't generate a default one unless you've saved it with the in-game config. The default config would look like (in `config/fabrishot.properties`)
```properties
#Fabrishot screenshot config
#Tue Jul 27 14:06:38 AEST 2021
custom_filename_format=true
width=3840
override_screenshot_key=false
height=2160
```

I'll add a patch to generate one by default

**Comment by ramidzkh** [comment]
Closed by https://github.com/ramidzkh/fabrishot/commit/493e8ac639d5c6c61751d39d395b1e55c3fdce77

**Comment by Pythagoras-314** [comment]
Yea I guess on Mac the config file doesn't generate unless mod loader is enabled.
