### ISSUE TITLE
A way to cancel saving the screenshot

### ISSUE THREAD

**Issue by ImUrX** [ramidzkh/fabrishot#26]
I'm doing a mod for saving to clipboard and wanted to be able to cancel saving it to a file so only to have it on the clipboard

**Comment by ramidzkh** [comment]
You can use https://github.com/comp500/ScreenshotToClipboard to save to the clipboard. I guess I can also add an option to cancel saving the file

**Comment by ImUrX** [comment]
Yeah I know about comp's version, had this idea for a while and later discovered it xD, with the cancel option I would be pretty much thankful
