### ISSUE TITLE
Option for Delay

### ISSUE THREAD

**Issue by FireController1847** [ramidzkh/fabrishot#27]
Hey there, I have a feature request I don't know if you'd be willing to implement or not. So basically, I want to be able to set a small delay before the screenshot is actually taken (but AFTER the resolution is set). That way, when using shaderpacks that have an auto exposure feature, it has time to fix the exposure before the screenshot is taken. As of right now, with this feature enabled, screenshots look like so:
![huge_2022-02-04_15 25 58](https://user-images.githubusercontent.com/16494272/152611556-e38fe9e3-f196-47a0-93f0-53c24475e16f.png)

Anywhere from 3-10 seconds should be plenty, but I figure a configurable option from 0-15 could be perfect

If no, no worries! But just wanted to throw this idea out there, thanks for your work on this mod!!

**Comment by FireController1847** [comment]
You're awesome, thank you tons!

**Comment by ramidzkh** [comment]
no problem :)
