### ISSUE TITLE
[Feature Request] : Option or Default Hide UI on Snapshot

### ISSUE THREAD

**Issue by CodexEnt** [ramidzkh/fabrishot#29]
.

**Comment by Obscure2020** [comment]
I'd like to second this request. I was gonna call it "Auto-F1". An option to automatically hide all the UI when the Huge Screenshot key is pressed would be fantastic.

**Comment by Obscure2020** [comment]
Hey, thanks for implementing this! Just tested it out, and it worked exactly as I had hoped.
