### ISSUE TITLE
[Feature Request]: Custom or More Detail in Snapshot file name

### ISSUE THREAD

**Issue by CodexEnt** [ramidzkh/fabrishot#30]
Hi. Right now the resultant name from a snapshot (assuming default 4k) is 

eg. huge_2022-03-16_{time_stamp}.png

At least, I would like the ModPackName and WorldName included, as it is far more descriptive, and maybe other namings could be included in settings panel depending on end use.

{ModPackName} _(optional)__{WorldName}_{PlayerName}_(optional)__{Date:Time}

Maybe {ServerName}_(optional)_ for server admins/moderators who might need to take screenshots for any reason.

I may for some reason want to move the screenshots I take in individual instances and  modpacks and put them in my general Images/Games/Minecraft  folder, where you might see that the current naming convention wouldn't mean much in the long run, as I will delete or uninstall past modpacks and wouldn't want to try to remember or rename where these snapshots came from.

Also, perhaps some file format options to save to more compressed formats like the usual jpg, and newer *.webm if uploading to web, and newer compression formats *.avif and *.heic if desired and time allows.

Just adding to the original poster's thoughts as to why more naming conventions would be handy.

**Comment by ramidzkh** [comment]
This is probably the for ffmpeg/imagemagik

**Comment by ramidzkh** [comment]
I could probably do JPEG though

**Comment by ramidzkh** [comment]
PNG, JPEG, and BMP are built in now. Use external tools for for webm stuff; Minecraft doesn't come with encoders for those.
