### ISSUE TITLE
[Feature Request]: Keep GUI size in high resolution screenshots

### ISSUE THREAD

**Issue by thouu** [ramidzkh/fabrishot#32]
When I take a 4k screenshot, the GUI, such as my hotbar & crosshair, doesn't scale properly with the screenshot and it makes it [look rather weird](https://imgur.com/a/6odFxdA).

I think it would be nice to have an option to have the GUI size remain the same, but have the main content of the image be taken at 4k. I believe Optifine's x4 screenshot feature does this by default.

**Comment by RaptaG** [comment]
Yes please fix that!

**Comment by TechPro424** [comment]
yes please

**Comment by RaptaG** [comment]
@ramidzkh sorry for the ping, but is there any progress with this?

**Comment by ramidzkh** [comment]
I'm unsure how to fix this and it's a low priority for me. Might need to do stuff which breaks custom UI mods
