### ISSUE TITLE
[Compatibility] Nicephore - conflict with auto-clipboarding feature

### ISSUE THREAD

**Issue by LotuxPunk** [ramidzkh/fabrishot#33]
Hey ! I'm the author of Nicephore and a user is reporting me a compatibility issue between our mods:

> So I realized I was using Fabrishot to overwrite the the vanilla screenshot, apparently Nicephore only recognize vanilla screenshots, but as soon Fabrishot overwrites it with its own screenshot function, the "copy to clipboard" stopped working and throw the error just like in the video I sent
Just to recognize how Fabrishot overwrites vanilla screenshot, the video 12 days ago I sent above also show me took a screenshot, as a flash occured, that was Fabrishot overwrite function, which is togglable in the settings
So for now, I think making a compatible with Fabrishot should help, or depend on the player, like me, to not use the overwrite function and just let the mod capture screenshot with a different hotkey beside vanilla one (default for the mod is F9, vanilla is F2)

Source : https://github.com/LotuxPunk/Nicephore-Fabric/issues/10#issuecomment-1099457717

Can we maybe work together on this ? 👀

**Comment by ramidzkh** [comment]
There is ScreenshotSaveCallback, maybe you can hook into that if Fabrishot is detected?
