### ISSUE TITLE
[Feature request] Auto-exposure shader support

### ISSUE THREAD

**Issue by lenrik1589** [ramidzkh/fabrishot#36]
Some shaderpacks allow to use "Auto exposure", where shaderpack will change exposure based on previous several frame buffers but initial exposure is usually way too high so screenshots taken with fabrishot usually are heavily overexposed:
![2022-05-28_23 19 00](https://user-images.githubusercontent.com/48890625/170841654-02941c0e-ff8b-44f9-9e5e-e694ba29e90a.png)
same screenshot but a second after buffer has been reset:
![2022-05-28_23 18 59](https://user-images.githubusercontent.com/48890625/170841635-9ce15b6f-cfd5-436e-9c5a-2b8576d2672e.png)
As such i request a setting to be added which would allow user to specify period after which to take screenshot and reset buffer size

**Comment by lenrik1589** [comment]
Am i an idiot? maybe. does #34 have a name i wouldn't think is related to auto-exposure? yes…

**Comment by ramidzkh** [comment]
I'll add that to the tooltip for capture delay
