### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ShabanPlayz** [ramidzkh/fabrishot#4]
This mod is not working at all for me, please tell me what information you require from me to be able to fix this issue.

**Comment by ramidzkh** [comment]
Your GPU, OS and mod list. Also, if you have Optifine, check if it works without Optifine.

**Comment by ShabanPlayz** [comment]
I have an I5-4210U with integraded graphics and my OS is Windows 10. I just booted up fabric with just fabric api and fabrishot so it's definetly not a mod incompatibility issue.

**Comment by ShabanPlayz** [comment]
I just had the idea that this might be an issue with Java 15 so I switched to Java 8 and it's still not working.

**Comment by ShabanPlayz** [comment]
You might want to add the information that this mod requires you to press a different key to the mod's description.
