### ISSUE TITLE
Minecraft crashing when taking screenshots

### ISSUE THREAD

**Issue by TechPro424** [ramidzkh/fabrishot#45]
Whenever I take a screenshot with fabrishot (I have normal screenshots replaced with Fabrishot) I get this crash. It happens on every server I visit as well as in single player.

Here are the `latest.log` and crash report files: https://gist.github.com/TechPro424/c3c65510afdd34e1b95d52fa4a6b3804

**Comment by ramidzkh** [comment]
Whoops. You can wait around half an hour for the update or edit `config/fabrishot.properties` and add `custom_file_name=huge_%time%` on a new empty line

**Comment by ramidzkh** [comment]
Or you can use the mod jar found in https://github.com/ramidzkh/fabrishot/suites/8603896828/artifacts/385778199
