### ISSUE TITLE
Support 1.19.4 on Modrinth (and CurseForge, probably?)

### ISSUE THREAD

**Issue by NyaomiDEV** [ramidzkh/fabrishot#53]
This mod works on 1.19.4, but Modrinth doesn't know it yet, and this fact kinda is preventing users who don't know it to use it.

So, yeah, probably the latest version should be marked as compatible with the latest update.

**Comment by ramidzkh** [comment]
[Modrinth](https://modrinth.com/mod/fabrishot/version/1.9.2) [CurseForge](https://curseforge.com/minecraft/mc-mods/fabrishot/files/4506019)
