### ISSUE TITLE
Name of saved pictures

### ISSUE THREAD

**Issue by QueenUlyana** [ramidzkh/fabrishot#57]
I want the pictures to be saved with a normal name, without adding "huge". Can you do this option? Since with "huge", finding new pictures for me becomes more difficult or make a separate folder for saving pictures with your mod.
![2023-05-28_131348](https://github.com/ramidzkh/fabrishot/assets/83131824/ac27aaad-a8de-4ee4-9608-3b5c38ef3770)

**Comment by ramidzkh** [comment]
Change the format in the config
