### ISSUE TITLE
[Feature Request] Make the UI scaling not change an option

### ISSUE THREAD

**Issue by Julienraptor01** [ramidzkh/fabrishot#59]
I liked the fact that the UI scaling wouldn't change, could you tweak the change you did to make it optional ?
https://github.com/ramidzkh/fabrishot/pull/52/commits/dcfc8ee21a1a8ef391891ed90d89309e0af15186

**Comment by ramidzkh** [comment]
Uhh, just rollback fabrishot for now. I guess I could add an option for it

**Comment by Julienraptor01** [comment]
Thanks 👍
