### ISSUE TITLE
Animation looks very broken and clearly unintended in combination with "Slight" GUI Modification's satisfying screenshot animation

### ISSUE THREAD

**Issue by CalXee** [ramidzkh/fabrishot#6]
Pressing F9 with the feature enabled in that mod would cause the screenshot animation to appear very broken.

Mod link: https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications

**Comment by ramidzkh** [comment]
It doesn't look like shedaniel is interested in adding support unfortunately :(
