### ISSUE TITLE
Wepb extension

### ISSUE THREAD

**Issue by CormacZ** [ramidzkh/fabrishot#62]
Add .webp as an option to take screenshot

**Comment by ramidzkh** [comment]
WEBP isn't inside STB (and [unlikely](https://github.com/nothings/stb/issues/464) to be, [ever](https://github.com/nothings/stb/issues/931)), and I'm probably not going to bundle a webp compressor. Anyway, doesn't webp have way too many configuration options to be part of this mod anyway? Just pass your screenshots through ffmpeg or something
