### ISSUE TITLE
Fabrishot 1.10.0 for MC 1.20.1 wrong version tag

### ISSUE THREAD

**Issue by Tapacywka** [ramidzkh/fabrishot#63]
![image](https://github.com/ramidzkh/fabrishot/assets/71761232/dcfaa63c-ee72-4370-a2cb-9c5f59c82132)

**Comment by ramidzkh** [comment]
Ah, fixed

**Comment by Tapacywka** [comment]
Versions of dependencies are also incorrect, xd
![image](https://github.com/ramidzkh/fabrishot/assets/71761232/3dffed5c-55c9-4a10-a300-528dfa082b5e)
