### ISSUE TITLE
Fabrishot not working (maybe i'm just confused)

### ISSUE THREAD

**Issue by redstonerti** [ramidzkh/fabrishot#7]
I have mod options and cloth config and it doesn't allow for configuration
Did i do something wrong?
https://imgur.com/a/L5KU2bY

**Comment by ramidzkh** [comment]
There should be a button on top of the issues button

**Comment by redstonerti** [comment]
> There should be a button on top of the issues button

that's my problem. There isn't

**Comment by ramidzkh** [comment]
You're using cloth config forge. Download the fabric version

**Comment by redstonerti** [comment]
Yeah you're right
Somebody on discord pointed it out and now it works. Sorry for the inconvenience

**Comment by Madis0** [comment]
As of Fabrishot v1.2.3 I see the config button, but it says "You must install Cloth Config", but I do have Cloth Config v4.8.3 according to the mod menu.
