### ISSUE TITLE
"Save the screenshot file"?

### ISSUE THREAD

**Issue by Madis0** [ramidzkh/fabrishot#71]
The mod has an option called "Save the screenshot file". What is the point of that?
Why wouldn't the user just remove the mod or unbind the keybind if they don't want to use it at a certain time?

**Comment by ramidzkh** [comment]
There (used to be?) integration with [ScreenshotToClipboard](https://github.com/comp500/ScreenshotToClipboard), see #11 and #26

**Comment by Madis0** [comment]
Got it.
