### ISSUE TITLE
Allow 1.20.6 - It's just a bug fix

### ISSUE THREAD

**Issue by Mukul1127** [ramidzkh/fabrishot#84]
Currently the mod doesn't support 1.20.6 though 1.20.6 is basically a bug fix of 1.20.5, just one change, so update would be appreciated.

**Comment by ramidzkh** [comment]
Marked as working on 1.20.6 on CF and Modrinth

**Comment by ramidzkh** [comment]
Actually nvm that won't work I need a proper update :( 1 sec

**Comment by ramidzkh** [comment]
1.13.1 is marked compatible for 1.20.6
