### ISSUE TITLE
[Feature Request] Option to remove pause menu text

### ISSUE THREAD

**Issue by rabywastaken** [ramidzkh/fabrishot#86]
Hello, I'd like to request an option to remove the "Take 4k screenshots with F9" text from the pause menu.
![image](https://github.com/ramidzkh/fabrishot/assets/31973406/f2cc8ba7-c9e5-470c-8068-f91162f14733)

**Comment by ramidzkh** [comment]
Hi, Fabrishot isn't the mod which adds this text. Perhaps you are playing a modpack which adds this text? If so, please ask the modpack authors for help

**Comment by rabywastaken** [comment]
> Hi, Fabrishot isn't the mod which adds this text. Perhaps you are playing a modpack which adds this text? If so, please ask the modpack authors for help

Oh, I see, I'm indeed playing a modpack (Fabulously Optimized), but even when I tried removing all the custom resource packs, the message was still there... I'll try and figure it out when I get on my laptop tomorrow 👍
