### ISSUE TITLE
1.21.1 Support

### ISSUE THREAD

**Issue by RoonMoonlight** [ramidzkh/fabrishot#92]
Hello, Minecraft 1.21.1 is out and when I try to launch the game with 1.21.1 the Loader says it is incompatible as it still depends on 1.21. Would be great if this mod can be updated with 1.21.1. Also this update only includes hotfix it shouldn't be a problem updating the mod, only for dependency.

Thank you as always

**Comment by Mukul1127** [comment]
you can use a dependency override to launch the game
